# Generated by Django 4.1.4 on 2024-02-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=45)),
                ('tooth1', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth2', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth3', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth4', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth5', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth6', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth7', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth8', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth9', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth10', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth11', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth12', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth13', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth14', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth15', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth16', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth17', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth18', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth19', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth20', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth21', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth22', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth23', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth24', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth25', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth26', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth27', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth28', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth29', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth30', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth31', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
                ('tooth32', models.CharField(choices=[('Healthy', 'Healthy'), ('Stained', 'Stained'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ('name',),
            },
        ),
    ]
