# Generated by Django 4.1.4 on 2024-02-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='tooth1',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth10',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth11',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth12',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth13',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth14',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth15',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth16',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth17',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth18',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth19',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth2',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth20',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth21',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth22',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth23',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth24',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth25',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth26',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth27',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth28',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth29',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth3',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth30',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth31',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth32',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth4',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth5',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth6',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth7',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth8',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth9',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Cavities', 'Cavities'), ('Chipped', 'Chipped'), ('Crooked', 'Crooked'), ('Gingivitis', 'Gingivitis')], default='Healthy', max_length=45),
        ),
    ]
